### ISSUE TITLE
Test Failure: network configuration when using manual networking deploys multiple manual networks

### ISSUE THREAD

**Issue by dmutreja** [oracle/bosh-oracle-cpi#10]
BATs test failure 

rspec ./spec/system/network_configuration_spec.rb:73

**Comment by dmutreja** [comment]
[test output log](https://github.com/oracle/bosh-oracle-cpi/files/1433657/all-tests.log)

**Comment by dmutreja** [comment]
Excerpt from chat with dkalinin. 
>dmutreja [6:19 PM] 
Can someone please help me understand the intent behind this test https://github.com/cloudfoundry/bosh-acceptance-tests/blob/3ae1a3d9fe615f34fca9022d204f291304709443/spec/system/network_configuration_spec.rb#L75 ?
dkalinin [6:26 PM] 
@dmutreja i think this is to check if iaas can attach multiple nics to the same machine
```
Generated deployment manifest:
---
name: bat
releases:
- name: bat
  version: latest
compilation:
  workers: 2
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_shape: VM.Standard1.2
    availability_domain: WZYX:PHX-AD-3
update:
  canaries: 1
  canary_watch_time: 3000-90000
  update_watch_time: 3000-90000
  max_in_flight: 1
networks:
- name: default
  type: manual
  subnets:
  - range: 10.0.9.0/24
    reserved:
    - 10.0.9.2 - 10.0.9.9
    static:
    - 10.0.9.10 - 10.0.9.30
    gateway: 10.0.9.1
    dns:
    - 169.254.169.254
    cloud_properties:
      vcn: cloudfoundry_vcn
      subnet_name: bats_subnet1_ad3
- name: second
  type: manual
  subnets:
  - range: 10.0.10.0/24
    reserved:
    - 10.0.10.2 - 10.0.10.9
    static:
    - 10.0.10.10 - 10.0.10.30
    gateway: 10.0.10.1
    dns:
    - 169.254.169.254
    cloud_properties:
      vcn: cloudfoundry_vcn
      subnet_name: bats_subnet2_ad3
resource_pools:
- name: common
  network: default
  stemcell:
    name: light-oracle-ubuntu-stemcell
    version: latest
  cloud_properties:
    instance_shape: VM.Standard1.2
    availability_domain: WZYX:PHX-AD-3
jobs:
- name: batlight
  templates:
  - name: batlight
  instances: 1
  resource_pool: common
  networks:
  - name: default
    default:
    - dns
    - gateway
    static_ips:
    - 10.0.9.30
  - name: second
    static_ips:
    - 10.0.10.30
properties:
  batlight:
    missing: nope
```
>dkalinin
that looks about right
[6:40] 
2 networks attached, 2 networks defined
[6:40] 
doesnt matter how many subnets are set in each network
dmutreja [6:41 PM] 
ok, so maybe there is a bug in the CPI implementation.   WIll create_vm get both networks? And the expectation is that both will be attached to the new vm?
[6:42] 
@dkalinin ^
dkalinin [6:43 PM] 
yup
