### ISSUE TITLE
Add `info` method to CPI

### ISSUE THREAD

**Issue by dpb587-pivotal** [oracle/bosh-oracle-cpi#20]
Hi - we noticed the CPI doesn't support the [`info`](http://bosh.io/docs/cpi-api-v1.html#info) endpoint that director is starting to use. Currently, the only use case of `info` right now is so director can ask which types of stemcells a CPI supports. When operators are utilizing [multi-cpi](http://bosh.io/docs/guide-multi-cpi-aws.html) support, we only want to give uploaded stemcells to CPIs which support them. When someone uploads a stemcell, director executes `info` and checks what formats are returned in the `stemcell_formats` value and checks if the stemcell tarball listed any of the same formats. When `stemcell_formats` is missing from CPI `info` or stemcell tarball, the `create_stemcell` call will be executed regardless (which is why it still continues to work when a single CPI is used).

The stemcell format convention is `{iaas}-{image-format}`. For example, to support your light stemcell, you probably want to be returning `oracle-light`. And to support the original heavy stemcell, it might be `oracle-rawdisk` (let us know if you need advice).

This may actually involve changes to how you build stemcells as well. It looks like your light stemcell tarballs don't include a `stemcell_formats` yet. Here's an example of what it might need to be updated with...

```yaml
name: light-oracle-ubuntu-stemcell 
version: 2000.13
bosh_protocol: '1'
sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
operating_system: ubuntu
cloud_properties:
  ...
stemcell_formats:
- oracle-light
```

Since your CPI is golang-based, you might want to take a look at [this change](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/pull/243/files) to add support to the Google CPI. I think the changes should be fairly similar.

If you have any questions, feel free to ping us in [#bosh](https://cloudfoundry.slack.com/messages/C02HPPYQ2/)/[cloudfoundry#oracle](https://cloudfoundry.slack.com/messages/C7P97LNFL/) or ask questions here and we'll be happy to help!

/cc @cppforlife
